preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  com.android.application:
    alias: android-application
    version: +
  com.android.library:
    alias: android-library
    version-ref: com.android.application
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version: +

libraries:
  com.highcapable.betterandroid:
    ui-component:
      version: +
    ui-extension:
      version: +
    system-extension:
      version: +
    compose-extension:
      version: +
  com.highcapable.flexiui:
    core-android:
      version: +
      # Flexi UI is in alpha stage for now.
      version-filter:
        use-internal: false
  androidx.compose:
    compose-bom:
      version: +
  androidx.compose.ui:
    ui:
      version: <no-spec>
    ui-graphics:
      version: <no-spec>
    ui-tooling:
      version: <no-spec>
    ui-tooling-preview:
      version: <no-spec>
  androidx.compose.foundation:
    foundation:
      version: <no-spec>
  androidx.navigation:
    navigation-compose:
      version: +
  androidx.activity:
    activity:
      version: +
    activity-compose:
      version: +
  junit:
    junit:
      version: +
  androidx.test.ext:
    junit:
      version: +
  androidx.test.espresso:
    espresso-core:
      version: +